<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11912" started-at="2013-01-20T17:30:38Z" finished-at="2013-01-20T17:30:50Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11912" started-at="2013-01-20T17:30:38Z" finished-at="2013-01-20T17:30:50Z">
      <class name="com.mac.example.Seltest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.mac.example.Seltest@147ee05]" name="setUp" is-config="true" duration-ms="11745" started-at="2013-01-20T12:30:38Z" finished-at="2013-01-20T12:30:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testDataProviderExample(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.mac.example.Seltest@147ee05]" name="testDataProviderExample" duration-ms="0" started-at="2013-01-20T12:30:50Z" data-provider="DP1" finished-at="2013-01-20T12:30:50Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void com.mac.example.Seltest.testDataProviderExample(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception requires a @DataProvider named : DP1]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void com.mac.example.Seltest.testDataProviderExample(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception requires a @DataProvider named : DP1
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:265)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:415)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1384)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:128)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1203)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.run(TestNG.java:1036)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDataProviderExample -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.mac.example.Seltest@147ee05]" name="tearDown" is-config="true" duration-ms="152" started-at="2013-01-20T12:30:50Z" finished-at="2013-01-20T12:30:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.mac.example.Seltest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
